# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [2]:
from scipy import stats 
import numpy as np

In [3]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [18]:
GPU1Mean = GPU1.mean()
#H0:GPU1Mean = 0
#Ha:GPU1Mean != 0
mu=0
print('Sample Mean', GPU1Mean)
s=np.std(GPU1)
n = GPU1.size
se = s/np.sqrt(n-1)
print(s, n, se)
print(stats.t.isf(0.05,df=n-1,loc=98.6,scale=se))
print("P-Value")
print(2*(1-stats.t.cdf(GPU1Mean, df=n-1, loc=0, scale=se)))
print("T-statistics")
print((GPU1Mean-mu)/se)

Sample Mean 10.333333333333334
1.1352924243950933 15 0.3034196632775998
99.13441612832422
P-Value
7.105427357601002e-15
T-statistics
34.056241516158195


In [13]:
#Alternate method by direct formula
from scipy.stats import ttest_1samp
t_statistic, p_value = ttest_1samp(GPU1, 0)
print('T-Statistics', t_statistic)
print('P-Value', p_value)

T-Statistics 34.056241516158195
P-Value 7.228892044970457e-15


In [ ]:
#Since P-Value is less then the significance limit of 5% hence the decission is to reject the null Hypothesis

## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [30]:
#Ho=GPU1Mean-GPU2Mean = 0
#Ha=GPU1Mean-GPU2Mean != 0
t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU2)
print('T-Statistics', t_statistic)
print('P-Value', p_value)

T-Statistics -2.627629513471839
P-Value 0.013794282041452725


In [ ]:
# Since the P value is lower than 5% significance value hence reject the null hypothesis
# Which means the GPU1Mean is significantly different to GPU2Mean

## Question 3

He is trying a third GPU - GPU3.

In [27]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [29]:
#Ho=GPU1Mean-GPU3Mean = 0
#Ha=GPU1Mean-GPU3Mean != 0
t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU3)
print('T-Statistics', t_statistic)
print('P-Value', p_value)

T-Statistics -1.4988943759093303
P-Value 0.14509210993138993


In [ ]:
#Since P Value is greater than 5% significance value hence accept the null hypothesis
#Hence GPU3Mean is significantly different to GPU1Mean

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [32]:
import numpy as np
from scipy import stats 

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [33]:
#H0=All the sample are of equal variances i.e All means are equal
#Ha=The sample of population and not equals 
stats.levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

In [ ]:
#Since the P-Value is more than the significance value of 5% hence the null hypothesis cannot be rejected
#Hence samples are of equal variances

# Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [35]:
#H0=e1Mean ~ e2Mean ~e3Mean
#HA=One or more means are significantly different
stats.f_oneway(e1,e2,e3)

F_onewayResult(statistic=2.51357622845924, pvalue=0.13574644501798466)

In [ ]:
# Since the P-Value is higher than significant value of 5% hence the null hypothesis can't be rejected
# Hence the Means of population are equal.

# Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

TypeI: TypeI error is when the null hypothesis is true reject the hypothesis probablity of which is equal to significance level.

TypeII: TypeII error is when the null hypothesis is false but we fail to reject the null hypothesis

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


H0=The waiting time for placing an order has not changed significantly in the past month

Ha=The waiting time for placing the order has changed significantly in past month

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [37]:
import numpy as np
# Here d1 to d6 are the number of dice and four values in each dice represents value of dice for player 1 to player 4

d1 = [1, 6, 3, 4]
d2 = [2, 5, 1, 3]
d3 = [4, 2, 3, 1]
d4 = [3, 4, 1, 2]
d5 = [1, 6, 3, 5]
d6 = [3, 2, 2, 1]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [40]:
contingency = stats.chi2_contingency(dice) 
print('chi2stat', contingency[0])
print('p-value', contingency[1])
print('degree of freedom', contingency[2])
print('contingency', contingency[3])

chi2stat 11.445004959326388
p-value 0.720458335452983
degree of freedom 15
contingency [[2.88235294 5.14705882 2.67647059 3.29411765]
 [2.26470588 4.04411765 2.10294118 2.58823529]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [3.08823529 5.51470588 2.86764706 3.52941176]
 [1.64705882 2.94117647 1.52941176 1.88235294]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [54]:
#Get the zscore
zscore = stats.zscore(dice)
print('zscore', zscore)
#Get p-value from zscore
p_value= stats.norm.sf(abs(zscore))*2#
print('p-value', p_value)
#Mean of p-value
mean = p_value.mean()
print(mean)

zscore [[-1.20604538  1.09454091  0.92847669  0.89442719]
 [-0.30151134  0.4975186  -1.29986737  0.2236068 ]
 [ 1.50755672 -1.29354835  0.92847669 -1.11803399]
 [ 0.60302269 -0.09950372 -1.29986737 -0.4472136 ]
 [-1.20604538  1.09454091  0.92847669  1.56524758]
 [ 0.60302269 -1.29354835 -0.18569534 -1.11803399]]
p-value [[0.22779999 0.27371782 0.35316035 0.37109337]
 [0.7630246  0.61882339 0.19364643 0.82306327]
 [0.13166802 0.19582147 0.35316035 0.26355248]
 [0.5464936  0.92073834 0.19364643 0.65472085]
 [0.22779999 0.27371782 0.35316035 0.11752487]
 [0.5464936  0.19582147 0.85268368 0.26355248]]
0.4047868758983743


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [55]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [58]:
#H0=Treatment works
#Ha=Failed to prove treatment works
stats.ttest_rel(before, after)

Ttest_relResult(statistic=2.61701358701584, pvalue=0.009139398578192848)

In [59]:
#Since the pvalue is lower than the significant level, it fails the null hypothesis hence treatment does not work